os: linux
services:
  - docker
sudo: required

language: c

matrix:
  include:
    - os: linux
      language: c
      compiler: clang-3.8
      env: C_COMPILER="clang-3.8"
      addons:
        apt:
          sources:
            - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main"
              key_url:    "http://apt.llvm.org/llvm-snapshot.gpg.key"
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.8
            - libtool
    - os: linux
      language: c
      compiler: clang-3.9
      env: C_COMPILER="clang-3.9"
      addons:
        apt:
          sources:
            - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main"
              key_url:    "http://apt.llvm.org/llvm-snapshot.gpg.key"
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.9
            - libtool
    - os: linux
      language: c
      compiler: clang-4.0
      env: C_COMPILER="clang-4.0"
      addons:
        apt:
          sources:
            - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main"
              key_url:    "http://apt.llvm.org/llvm-snapshot.gpg.key"
            - ubuntu-toolchain-r-test
          packages:
            - clang-4.0
            - libtool
    - os: linux
      language: c
      compiler: gcc-5
      env: C_COMPILER="gcc-5"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - libtool
    - os: linux
      language: c
      compiler: gcc-6
      env: C_COMPILER="gcc-6"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - libtool

    - os: osx
      osx_image: xcode8.2
      language: c
      env:
    - os: osx
      osx_image: xcode7.3
      language: c
      env:
    - os: osx
      osx_image: xcode7.1
      language: c
      env:
    - os: osx
      osx_image: xcode6.4
      language: c
      env:
    - os: osx
      osx_image: xcode6.2
      language: c
      env:


install:
  - ./.travis/install.sh
script:
  - ./.travis/run.sh