build: false

environment:
  PYTHON: "C:\\Python27"
  PYTHON_VERSION: "2.7.13"
  PYTHON_ARCH: "32"

  CONAN_UPLOAD: 1
  CONAN_REFERENCE: "apache-apr/latest"
  CONAN_USERNAME: "pbtrung"
  CONAN_CHANNEL: "testing"
  CONAN_TOTAL_PAGES: 1

  matrix:
    - CONAN_CURRENT_PAGE: 1

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan_package_tools ConfigParser
  - conan user

test_script:
  - python build.py